name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    
    - name: TypeScript setup
      run: npm install -D typescript @types/node

    - name: Notify Slack
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        TEXT: リリースされたよ！
      run: npm run post